

[selene]
base = "lua51"
name = "modding"


[server]
any = true

[client]
any = true

[username]
any = true

[constants]
any = true

[variables]
any = true


[graphics]
any = true
[timer]
any = true
[physics]
any = true
[keyboard]
any = true
[mouse]
any = true
[audio]
any = true
[image]
any = true
[system]
any = true


[utf8]
any = true

[assets]
any = true

[group]
any = true
[delay]
any = true
[array]
any = true
[exists]
any = true
[on]
any = true
[call]
any = true
[entities]
any = true
[inspect]
any = true


[register]
any = true
[save]
any = true
[load]
any = true
[serialize]
any = true
[deserialize]
any = true

[export]
any = true
[extend]
any = true

## Standard library modifications
[assert]
any = true

[math]
any = true

[table]
any = true



## mod-declared globals
[base]
any = true

## placement mod:
[placement]
any = true

## light mod:
[light]
any = true

## crafting mod:
[crafting]
any = true

## categories mod:
[categories]
any = true

## chat mod:
[chat]
any = true

## terrain mod:
[terrain]
any = true

## Slab ui mod:
[Slab]
any = true





## rgb chess:
[rgb]
any = true
