

[selene]
base = "lua51"
name = "modding"


[server]
any = true

[client]
any = true

[constants]
any = true

[variables]
any = true


[love]
any = true
[umg]
any = true




[utf8]
any = true


## Standard library modifications
[assert]
any = true

[math]
any = true

[table]
any = true



## mod-declared globals
[base]
any = true

## placement mod:
[placement]
any = true

## light mod:
[light]
any = true

## crafting mod:
[crafting]
any = true

## categories mod:
[categories]
any = true

## chat mod:
[chat]
any = true

## terrain mod:
[terrain]
any = true

## Slab ui mod:
[Slab]
any = true





## rgb chess:
[rgb]
any = true
