

[selene]
base = "lua51"
name = "modding"


[server]
any = true

[client]
any = true

[constants]
any = true

[variables]
any = true


[graphics]
any = true
[timer]
any = true


[assets]
any = true

[group]
any = true
[delay]
any = true
[set]
any = true
[array]
any = true
[exists]
any = true
[class]
any = true
[on]
any = true
[call]
any = true


## Standard library modifications
[assert]
any = true


