

[selene]
base = "lua51"
name = "modding"


[server]
any = true

[client]
any = true

[username]
any = true

[constants]
any = true

[variables]
any = true


[graphics]
any = true
[timer]
any = true
[physics]
any = true
[keyboard]
any = true
[mouse]
any = true


[assets]
any = true

[group]
any = true
[delay]
any = true
[set]
any = true
[array]
any = true
[exists]
any = true
[class]
any = true
[on]
any = true
[call]
any = true
[entities]
any = true
[inspect]
any = true

[serialize]
any = true
[deserialize]
any = true
[register]
any = true


## Standard library modifications
[assert]
any = true

[math]
any = true


