
--[[

define all mushrooms in here.


]]

local loc = localization.localize

---@alias lootplot.content.s0.MushArgs { property: string, buffAmount: number, description: string, buffType: "MULTIPLY" | "MODIFY"}

---@param image string
---@param name string
---@param args lootplot.content.s0.MushArgs
local function defineMush(image, name, args)
    return lp.defineItem("lootplot.content.s0:"..image, {
        image = image,
        name = loc(name),
        triggers = {"PULSE"},
        doomCount = 1,

        rarity = lp.rarities.UNCOMMON,
        minimumLevelToSpawn = 3,

        targetType = "SLOT",
        targetShape = lp.targets.ON_SHAPE,
        targetActivationDescription = loc(args.description),
        targetActivate = function(selfEnt, ppos, targetEnt)
            local slotEnt = lp.itemToSlot(selfEnt)
            if slotEnt then
                if args.buffType == "MULTIPLY" then
                    return lp.multiplierBuff(slotEnt, args.property, args.buffAmount, selfEnt)
                else
                    return lp.modifierBuff(slotEnt, args.property, args.buffAmount, selfEnt)
                end
            end
        end
    })
end

defineMush("mushroom_red", "Red Mushroom", {
    property = "pointsGenerated",
    buffAmount = 5,
    buffType = "MODIFY",
    description = "Gives +5 points-generated to slot",
})

defineMush("mushroom_purple", "Purple Mushroom", {
    property = "pointsGenerated",
    buffAmount = 2,
    buffType = "MULTIPLY",
    description = "Multiplies slot points-generated by 2",
})

defineMush("mushroom_green", "Green Mushroom", {
    property = "moneyGenerated",
    buffAmount = 1,
    buffType = "MODIFY",
    description = "Gives +1 money-generated to slot",
})

